---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Version 1.0.0
# Author: Vatu Ltd <hello@vatu.dev>

name: 'Commit'

on:

  workflow_dispatch:

  push:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  php-license:
    name: 'PHP Check licenses are compatible.'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.3']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Validate Composer file.'
        run: |
          composer validate --ansi --strict

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Caching.'
        uses: 'actions/cache@v5.0.2'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-build-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: 'Install dependencies.'
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Check licenses are compatible.'
        run: |
          composer run test:license

  php-security:
    name: 'PHP Security Analysis'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.3']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Validate Composer file.'
        run: |
          composer validate --ansi --strict

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Sets up Caching.'
        uses: 'actions/cache@v5.0.2'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-build-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: 'Install dependencies.'
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Run security test.'
        run: |
          composer run test:security

  php-validate:
    name: 'PHP Validate'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.3']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'xdebug'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Validate Composer file.'
        run: |
          composer validate --ansi --strict

  php-coding-standard:
    name: 'PHP Coding Standard'
    needs:
     - 'php-license'
     - 'php-security'
     - 'php-validate'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.3']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v5.0.2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: composer install --working-dir=tools --no-interaction --prefer-dist

      - name: 'Lint file syntax.'
        run: |
          composer run test:lint:php

      - name: 'PHP CodeSniffer with project rules.'
        run: |
          composer run test:lint:coding-standards

  php-static-analysis:
    name: 'PHP Static Analysis'
    needs:
     - 'php-license'
     - 'php-security'
     - 'php-validate'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version:
         - '8.3'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v5.0.2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: |
          composer install --working-dir=tools --no-interaction --prefer-dist
          composer install --no-interaction --prefer-dist

      - name: 'Test Static Analysis'
        run: |
          composer run test:analysis

  php-compatibility:
    name: 'PHP Compatiblity Tests'
    needs:
     - 'php-license'
     - 'php-security'
     - 'php-validate'
    continue-on-error: ${{ matrix.experimental }}
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'
        experimental: [false]
        # include:
        #   - php-version: '8.4'
        #     experimental: true

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v5.0.2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Run Compatibility tests.'
        run: |
          composer run test:compatibility -- --runtime-set testVersion ${{ matrix.php-version }}

  # code-coverage:
  #   name: 'PHP Code Coverage'
  #   needs:
  #    - 'php-unit-tests'
  #   runs-on: 'ubuntu-24.04'

  #   strategy:
  #     fail-fast: true
  #     max-parallel: 1
  #     matrix:
  #       php-version:
  #        - '8.3'

  #   steps:

  #     - name: 'Check out the repository.'
  #       uses: 'actions/checkout@v6.0.1'

  #     - name: 'Set up PHP environment.'
  #       uses: 'shivammathur/setup-php@2.36.0'
  #       with:
  #         coverage: 'pcov'
  #         ini-values: "memory_limit=-1"
  #         tools: 'composer'
  #         ini-file: none
  #         php-version: "${{ matrix.php-version }}"
  #       env:
  #         COMPOSER_TOKEN: ${{ secrets.github-token }}

  #     - name: 'Logs debug information.'
  #       run: |
  #         php --version
  #         composer --version

  #     - name: 'Get Composer Cache Directory.'
  #       id: 'composer-cache'
  #       run: |
  #         echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

  #     - name: "Sets up Caching."
  #       uses: "actions/cache@v5.0.2"
  #       with:
  #         path: ${{ steps.composer-cache.outputs.dir }}
  #         key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-php-composer-tools-

  #     - name: "Install dependencies."
  #       run: |
  #         composer install --no-interaction --prefer-dist

  #     - name: 'Code Coverage'
  #       run: |
  #         composer run test:unit -- --colors=always --coverage-text --coverage-clover build/logs/clover.xml

  #     - name: 'Upload coverage to Codecov'
  #       uses: 'codecov/codecov-action@v4.5.0'
  #       with:
  #         files: build/logs/clover.xml
  #         token: ${{ secrets.CODECOV_TOKEN }}

  php-unit-tests:
    name: 'PHP Unit Tests'
    needs:
      - 'php-coding-standard'
      - 'php-static-analysis'
      - 'php-compatibility'
    continue-on-error: ${{ matrix.experimental }}
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'
        experimental: [false]
        # include:
        #   - php-version: '8.4'
        #     experimental: true

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up PHP environment.'
        uses: 'shivammathur/setup-php@2.36.0'
        with:
          coverage: 'none'
          ini-values: "memory_limit=-1"
          tools: 'composer'
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: 'Logs debug information.'
        run: |
          php --version
          composer --version

      - name: 'Get Composer Cache Directory.'
        id: 'composer-cache'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v5.0.2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: |
          composer install --no-interaction --prefer-dist

      - name: 'Run Unit tests.'
        run: |
          composer run test:unit -- --colors=always --no-coverage

  npm-license:
    name: 'NPM Check licenses are compatible.'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        node-version: ['24']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up Node environment.'
        uses: 'actions/setup-node@v6.2.0'
        with:
          node-version: "${{ matrix.node-version }}"
          token: ${{ secrets.github-token }}
          cache: 'npm'

      - name: 'Logs debug information.'
        run: |
          node --version
          npm --version

      - name: 'Install dependencies.'
        run: |
          npm install

      - name: 'Run security test.'
        run: |
          npx license-checker --onlyAllow "BSD-2-Clause;BSD-3-Clause;GPL-2.0-or-later;LGPL-3.0-or-later;MIT;ISC;Apache-2.0;CC0-1.0;Python-2.0;MPL-2.0;Public Domain" --production

  npm-security:
    name: 'NPM Security Analysis'
    runs-on: 'ubuntu-24.04'

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        node-version: ['24']

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v6.0.1'

      - name: 'Set up Node environment.'
        uses: 'actions/setup-node@v6.2.0'
        with:
          node-version: "${{ matrix.node-version }}"
          token: ${{ secrets.github-token }}
          cache: 'npm'

      - name: 'Logs debug information.'
        run: |
          node --version
          npm --version

      - name: 'Install dependencies.'
        run: |
          npm install

      - name: 'Run security test.'
        run: |
          npm audit --only=prod
